version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    volumes:
      - bot_data:/app/bot_data
    environment:
      TELEGRAM_BOT_TOKEN: "6128330581:AAFoevxsg_OUbvbAfsf8ZLyOCh346Mx-Nbc"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bot_data:
